### ISSUE TITLE
Doesn't work in Chrome when using with existing server, but works in Firefox

### ISSUE THREAD

**Issue by dehghani-mehdi** [gregberge/error-overlay-webpack-plugin#21]
Hi,

I have very simple [react starter kit](https://github.com/dehghani-mehdi/react-starter-kit). I followed [your simple instruction](https://github.com/smooth-code/error-overlay-webpack-plugin#usage) to add `error-overlay-webpack-plugin` then I add `throw new Error('Oops!');` to `Home` component's `constructor` to test your plugin, but it doesn't work and I got empty page.

**Comment by dehghani-mehdi** [comment]
Sorry, I found out what was wrong, it was my configuration not your plugin.

**Comment by dehghani-mehdi** [comment]
With Firefox everything is okay, but when I use 2 servers it doesn't work in Chrome.

More details:
1. Setup really simple website in IIS (just index.html) (IP: for ex. `192.168.1.100:500`)
2. Run Webpack dev server (`127.0.0.1:8080`)

In Chrome, if I visit `127.0.0.1:8080` everything works as expected
But If I visit `192.168.1.100:500`, I got blank page and error details only shows up in browser console.

In that `index.html` (_IIS one_) I put

`<script src='http://127.0.0.1:8080/bundle.js'></script>` (hot reloading works fine btw)

**Comment by dehghani-mehdi** [comment]
If you run Chrome using `chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security`, it works, but as you know it's not best solution.

**Comment by qinyuanbin** [comment]
I have the same problem

**Comment by neoziro** [comment]
Hello, a PR is welcome to try to fix it! Thanks!

**Comment by bertho-zero** [comment]
This is a CORS issue, we should be able to overload the sockOptions. (withCredentials and Access-Control-Allow-Origin)

**Comment by gregberge** [comment]
Outdated, feel free to open a new issue it if you meet that bug.
