### ISSUE TITLE
Is there any way to show overlay with the compiled stacktrace while sourcemap is being fetched?

### ISSUE THREAD

**Issue by mohsinulhaq** [gregberge/error-overlay-webpack-plugin#27]
Right now, there is quite a noticeable delay in overlay showing up because it waits until sourcemap is fetched and parsed. Can I somehow show the compiled version of stacktrace in the overlay until that process is done, so that the overlay opens up immediately on error? Just like redbox-react.

**Comment by mohsinulhaq** [comment]
@neoziro hi, could you please help me here?

**Comment by neoziro** [comment]
I noticed that too, but unfortunately I don't have any solution for it...

**Comment by gregberge** [comment]
Outdated, feel free to open a new issue it if you meet that bug.
