### ISSUE TITLE
JSX SyntaxError breaks this plugin

### ISSUE THREAD

**Issue by mnlj** [gregberge/error-overlay-webpack-plugin#28]
I've set it up in my test project according to the Usage section and when I try a reference error as in the example, it works correctly. However, if I for example remove random closing tag in JSX, things break:
![overlay1](https://user-images.githubusercontent.com/11228958/50913941-cdcb8480-1435-11e9-80ad-ae311246cf4f.png)
![overlay2](https://user-images.githubusercontent.com/11228958/50913944-d02dde80-1435-11e9-9a32-92ab239cbba6.png)

If you look at the second image, the weird part is
`GET https://localhost:3000/babel/parser/lib/index.js 404 (Not Found)` which is requested from "node_modules/react-error-overlay". this breaks things. If I create similar SyntaxError in a create-react-app test app, this doesn't happen and a proper Failed to compile error appears in the overlay. Any ideas?

**Comment by neoziro** [comment]
Hello I am sorry I don't have time to investigate the bug. I added the badge, if someone have time to investigate it, it is welcome!

**Comment by chrispcode** [comment]
Are you sure you have added the missing p tag. Just asking?

**Comment by mnlj** [comment]
@chrispcode this is not about my code, it's about error showing properly in overlay. Missing p tag was a simulated syntax error, if such error happens in create-react-app, it shows it in the error overlay just fine, if it happens using this plugin, it breaks because react-error-overlay dependency loads wrong babel js and the visual output is stuck on the ansi coded garbage error.

**Comment by tungpin** [comment]
@mnlj this problem may because of terminal color character
use `/(\u001b\[\d*m)/g` can replace color character
![image](https://user-images.githubusercontent.com/29981970/54079964-7ce6e800-4321-11e9-8148-9650e3728253.png)

**Comment by neoziro** [comment]
Thanks for the update @tungpin, feel free to submit a PR to fix this problem.

**Comment by gregberge** [comment]
Looks like it is fixed, feel free to reopen.
