### ISSUE TITLE
The new socket throws when using webpack-dev-middleware instead of dev-server

### ISSUE THREAD

**Issue by swernerx** [gregberge/error-overlay-webpack-plugin#33]
We are using SSR and build our own server based around `webpack-dev-middleware`. With the latest update we see a regular issue when loading the page:

  `http://localhost:3000/sockjs-node/info?t=1553005986947 404 (Not Found)`

Unfortunately, the new code breaks for us using our own set-up. Do you mind adding an option to not enable the socket by default?

**Comment by neoziro** [comment]
Hello @swernerx, thanks for your report! Could you submit a PR for it?

**Comment by swernerx** [comment]
Here we go, @neoziro https://github.com/smooth-code/error-overlay-webpack-plugin/pull/34

**Comment by gregberge** [comment]
Fixed
