### ISSUE TITLE
sockjs-node/info 404 when running devServer with proxy

### ISSUE THREAD

**Issue by donnysim** [gregberge/error-overlay-webpack-plugin#35]
I'm using devServer with proxy, so the url I access is not `localhost:port` but something like `project.test` etc. and it tries to fetch `http://project.test/sockjs-node/info` which results in 404, where it should instead try to reach `http://localhost:port/sockjs-node/info`. HMR, overlay and everything else seems to work fine, but there's this constant 404 error about url not found.

Is there something I'm missing in the configuration for this to access the correct route? I'm using v0.2.0

**Comment by neoziro** [comment]
Hello @donnysim, I don't have time to dig more in your issue. I hope someone else could help you...

**Comment by gregberge** [comment]
@vjpr answered.
