### ISSUE TITLE
hot loading is slow & taking long time to to display error message

### ISSUE THREAD

**Issue by skirankumar7** [gregberge/error-overlay-webpack-plugin#51]
**Found that delay while using this plugin.**

**I think more of the reason is devtool option
devtool: 'cheap-module-source-map'**

https://webpack.js.org/configuration/devtool/

**kindly refer this screenshot.**

**Will it is possible to make it work with devtool option which is built and rebuild options is fast and faster**

**Basically I have a question is like what is the dev tools do and what it's every option does which are in screenshot?**

![image](https://user-images.githubusercontent.com/42739670/64963996-ceb39080-d8b7-11e9-82fe-9077d96df677.png)

**_any thoughts, comments...
Please comment.
Thanks._**

**Comment by neoziro** [comment]
Hello @skirankumar7, to be honest I don't have the answer. If someone want to investigate it and find the answer he is welcome.

**Comment by gregberge** [comment]
Outdated, feel free to open a new issue it if you meet that bug.
