### ISSUE TITLE
Does it work with webpack-hot-middleware?

### ISSUE THREAD

**Issue by kacpak** [gregberge/error-overlay-webpack-plugin#56]
I'm using multi-compiler build with express and webpack-dev-middleware + webpack-hot-middleware.
I've added this plugin for each webpack config but I only see the native webpack-hot-middleware overlay. Is there something more that needs to be done? Or right now there is no support for this configuration?
Maybe this can be added? I could try to help if someone pointed me at what needs to be done to make it work.

**Comment by KevinGruber** [comment]
I have the same problem. I only see the hot-middleware-overlay

**Comment by gregberge** [comment]
@vjpr answered.
