### ISSUE TITLE
Anyway to not trigger this for all errors?

### ISSUE THREAD

**Issue by ntucker** [gregberge/error-overlay-webpack-plugin#57]
It would be great to not have an invasive overlay appear for *every* error. If we could specify a function that filters out errors we want to pass through this would be super useful.

We throw network errors, which get caught and handled by our error boundaries. So we'd like to not see overlays in this case, which is considered working perfectly:
```js
filter(error: any, caught: boolean) {
  return !caught && typeof error.status !== number;
}
```

**Comment by gregberge** [comment]
Hello @ntucker, PR welcome for this feature.

**Comment by gregberge** [comment]
Outdated, if needed please open a new issue.
