### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by fwh1990** [gregberge/error-overlay-webpack-plugin#67]
As we know `wepback@5` had been published some days ago, I hope that you can update `error-overlay-webpack-plugin` to compatible with latest webpack, thank you

**Comment by gregberge** [comment]
Not a surprise! I will not fix it on my own, if someone is interested, feel free to submit a PR.

**Comment by JamesGelok** [comment]
help wanted tag should be on this issue

**Comment by changkem** [comment]
it depends on react-dev-utils...but react-dev-utils not support webpack5 till now. see https://github.com/facebook/create-react-app/issues/9994

**Comment by dlimx** [comment]
`react-dev-utils` has removed it here https://github.com/facebook/create-react-app/pull/10198, waiting on release now

**Comment by Mitsunee** [comment]
for whatever it's worth I just went ahead and installed error-overlay-webpack-plugin in a local repo and it appears to be working fine there despite the warning yarn showed upon installing. If chalk getting introduced into the browser by a dependency was the only problem this seems to be fixed now.

**Comment by chang-ke** [comment]
> Not a surprise! I will not fix it on my own, if someone is interested, feel free to submit a PR.

Now I submit a PR

**Comment by gregberge** [comment]
Fixed in v1
