### ISSUE TITLE
Feature Request: Publish TypeScript Types

### ISSUE THREAD

**Issue by cinderblock** [gregberge/error-overlay-webpack-plugin#71]
Webpack supports `webpack.config.ts` these days. It would be very helpful to publish some typings. Ideally, these would be bundled in this package in the published sources.

Alternatively, one could (independently) publish to DefinitelyTyped to provide the types.

What is the appetite here for either:
1. Converting `src` to TypeScript
2. Adding hand created `.d.ts` files

**Comment by gregberge** [comment]
Typing what? There is only one class exposed 😅

**Comment by cinderblock** [comment]
So, would you reject a PR that adds them?

**Comment by gregberge** [comment]
> So, would you reject a PR that adds them?

No I will accept it.
