### ISSUE TITLE
react-dev-utils uses a vulnerable version of browserslist as a dependency

### ISSUE THREAD

**Issue by Redirts** [gregberge/error-overlay-webpack-plugin#73]
error-overlay-webpack-plugin uses a version of react-dev-utils that has unsafe browserslist version.
We will need this fixed first: https://github.com/facebook/create-react-app/issues/10928

**Comment by gregberge** [comment]
Everything is up to date here, please reopen this issue when the problem will be fixed in the other package, thanks!
