### ISSUE TITLE
Uncaught ReferenceError: process is  not defined

### ISSUE THREAD

**Issue by haquezameer** [gregberge/error-overlay-webpack-plugin#91]
Recently started getting the above error when using the `error-overlay-webpack-plugin`. It is probabaly happening due to [this](https://github.com/facebook/create-react-app/issues/11773) issue on `react-error-overlay` since `error-overlay-webpack-plugin` does not pin `react-error-overaly` to `6.0.9` so now new installations are getting the latest `react-error-overlay@6.0.10`.

Possible to do any fixes for the above issue in this package?

**Comment by eimantaszlabys** [comment]
I also get this error :( When this issue will be fixed? Maybe there is some other way to solve this issue?|
