### ISSUE TITLE
compatibility with both `ws` and `sockjs`

### ISSUE THREAD

**Issue by snitin315** [gregberge/error-overlay-webpack-plugin#96]
Currently, the plugin is using the `sockjs-client` for devServer which was default in `webpack-dev-server@3`.

https://github.com/gregberge/error-overlay-webpack-plugin/blob/8aa4edf623e1a893933334367d10c17c525a62a0/src/entries/devserver.mjs#L4
https://github.com/gregberge/error-overlay-webpack-plugin/blob/8aa4edf623e1a893933334367d10c17c525a62a0/src/entries/devserver.mjs#L13-L19

`webpack-dev-server@v4` changed the default to `ws`, it would be great if the plugin can support both. Otherwise we have errors in console with [`webSocketServer: 'ws'`](https://webpack.js.org/configuration/dev-server/#devserverwebsocketserver)

<img width="1317" alt="Screenshot 2022-02-21 at 11 15 22 AM" src="https://user-images.githubusercontent.com/46647141/155293230-8813ba22-307c-42e4-998d-43f653fd54ae.png">

**Comment by giladgd** [comment]
Until my fix PR (#105) is merged you can use this workaround:
```bash
npm install --save-dev "github:giladgd/error-overlay-webpack-plugin#wsErrorMessageFix/compiled"
```

This will install a branch I created with the fix and with compiled files to make it work properly as a node module
